### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by Croydon** [SpartanJ/SOIL2#36]
The last release is from 2017

Now, where we have Premake5 support and a changed license, it would be good to have a new release 😄

**Comment by SpartanJ** [comment]
Sure! I was testing a little bit, released [version 1.20](https://github.com/SpartanJ/SOIL2/releases/tag/release-1.20).

**Comment by Croydon** [comment]
Thanks!

// https://github.com/bincrafters/conan-soil2/commit/681cf3614976db0a4e093b0bd9500b43e54dad7d
