### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by RealLaraCroft** [SpartanJ/SOIL2#38]
I am using visual studio 2019 and whenever I try to compile I get this error coming from some of the SOIL2 files

`'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.`

how can I fix this I tried putting `#define _CRT_SECURE_NO_DEPRECATE` at the beginning of the offending files but it completely messed everything up. what can I do to fix this?

**Comment by SpartanJ** [comment]
This is an issue just with your own project configuration. The project generated with premake5 will work just fine. You just needed to add `_CRT_SECURE_NO_DEPRECATE` in your preprocessors: 
![Untitled](https://user-images.githubusercontent.com/650416/86500033-c227f800-bd64-11ea-9cee-1dfe70263122.png)
Regards
