### ISSUE TITLE
compiling SOIL2 with mingw64 gcc version 11.2.0

### ISSUE THREAD

**Issue by BihartStudio** [SpartanJ/SOIL2#50]
I am trying to compile SOIL2 with mingw64.
I have installed premake5 and used the following commands:

`premake5 gmake`
`cd make/windows`
`mingw32-make`

after which I get the following error:

mingw32-make
==== Building soil2-static-lib (debug_x86_64) ====
Creating ../../obj/windows/x86_64/debug/soil2-static-lib
mkdir: cannot create directory ‘..\\..\\obj\\windows\\x86_64\\debug\\soil2-static-lib’: No such file or directory
mingw32-make[1]: *** [soil2-static-lib.make:153: ../../obj/windows/x86_64/debug/soil2-static-lib] Error 1
mingw32-make: *** [makefile:45: soil2-static-lib] Error 2

Please help, as I do not want to use MSVC for my OpenGL projects.

**Comment by SpartanJ** [comment]
`mkdir: cannot create directory` that looks weird. The issue depends on your own configuration of mingw64 and the whole environment. From the error I don't have much information to help you. May be you can try to use premake4 that it seems more friendly to the mingw enviroments.

**Comment by micwoj92** [comment]
@BihartStudio try creating directory using `mkdir -p` instead of just `mkdir`
