### ISSUE TITLE
Compiler Error VS2022

### ISSUE THREAD

**Issue by blossomsg** [SpartanJ/SOIL2#51]
I have used the below command.
`.\premake5.exe --os=windows vs2022 --verbose`

when I try to build in vs2022 release x64 it gives me below error
when I debug x64 it succeeds

`Build started...
1>------ Build started: Project: soil2-static-lib, Configuration: release x64 ------
1>cl : command line warning D9025: overriding '/TC' with '/TP'
1>SOIL2.c
1>image_DXT.c
1>image_helper.c
1>wfETC.c
1>Generating Code...
1>D:\c_drive_installs\OpenGL_files\soil2\SOIL2\src\SOIL2\SOIL2.c(2247): fatal error C1001: Internal compiler error.
1>(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 220)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>If possible please provide a repro here: https://developercommunity.visualstudio.com
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information
1>Done building project "soil2-static-lib.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
`
any suggestions would be really helpful

**Comment by SpartanJ** [comment]
Hi, I don't have a windows installation to test the issue at the moment. The error code points to a [compiler error](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1001?view=msvc-170), reading on SO seems to be fixable on some occasions cleaning up the [project cache](https://stackoverflow.com/a/45455677). I'll take a look if I can reproduce it in the coming days.

**Comment by blossomsg** [comment]
Hey SpartanJ, Thank you for looking into this

**Comment by SpartanJ** [comment]
Updated locally to VS2022, and no issues appeared. I also actualized Github Actions and works fine with VS2022. It seems that you have a cache issue, try to clean up all your cached files (obj, project, etc).

**Comment by ShiHongyu6** [comment]
I have the same problem. It isn't resolved from removing output file and rebuild. 
I find the resolve from 'stack over flow' that is set up the project properties Optimization to Disabled(/Od).

**Comment by SpartanJ** [comment]
Hi @ShiHongyu6! I was able to circumvent the compiler bug by disabling optimizations only for the offending section. Now you should be able to build in release mode without making any changes.
