### ISSUE TITLE
lib version

### ISSUE THREAD

**Issue by bart9h** [SpartanJ/SOIL2#52]
Could you define SOIL2_VERSION_MAJOR, SOIL2_VERSION_MINOR, and SOIL2_VERSION_PATCH?

Or provide a `const char* SOIL_version();` function, or whatever?

**Comment by SpartanJ** [comment]
Added SOIL_version, which returns an unsigned long.
Added:
SOIL_MAJOR_VERSION: major version number,
SOIL_MINOR_VERSION: minor version number,
SOIL_PATCH_LEVEL: patch level version,
SOIL_VERSION_NUM: version number constructor,
SOIL_COMPILED_VERSION: compiled version number,
SOIL_VERSION_ATLEAST: version number checker.
