### ISSUE TITLE
SOIL2 is amazing but how without OpenGL ?

### ISSUE THREAD

**Issue by alexpanter** [SpartanJ/SOIL2#62]
So, the title says it all:

SOIL2 is amazing, and especially with DX10 support now it supports many of my use cases.

## But

I'm writing a library for Vulkan, and while I really do like the support coverage in SOIL2, I don't want to either include or link to OpenGL in any way.

Is there a way?

Most Vulkan sources simply import stb_image directly, then I need to add more dependencies for other formats (like DDS).
Most notably, Vulkan does not have built-in support for generating mip-maps, and I should not want to expose code in a Vulkan library which makes such a false promise.

## What I seek

SOIL2, just without all the OpenGL-stuff?

I would create my own image library if I have to, but I would rather save the time.
A set of functions that create a bunch of flat arrays from image file names or an input stream object sounds ideal to me.

**Comment by SpartanJ** [comment]
Hi Alexander!
SOIL2 is basically an OpenGL helper library for image/texture loading. Adding Vulkan support would be a pretty big change. I would love to add that support but I currently lack time to work on something like that, I'm working on other projects that are more useful for my current needs. So sorry but I can't do much about it! Good luck!

**Comment by alexpanter** [comment]
No problem, Thank you for the reply!
