### ISSUE TITLE
Not usable with nanovg

### ISSUE THREAD

**Issue by jjYBdx4IL** [SpartanJ/SOIL2#65]
Both projects are directly including stb. Not good. Maybe STB should be treated as every other lib and not as header only.

```
16:03:10:503	2>soil2.lib(SOIL2.c.obj) : error LNK2005: stbi_load_from_memory already defined in nanovg.lib(nanovg.c.obj)
16:03:10:503	2>soil2.lib(SOIL2.c.obj) : error LNK2005: stbi_load_from_callbacks already defined in nanovg.lib(nanovg.c.obj)
16:03:10:503	2>soil2.lib(SOIL2.c.obj) : error LNK2005: stbi_load already defined in nanovg.lib(nanovg.c.obj)
16:03:10:503	2>soil2.lib(SOIL2.c.obj) : error LNK2005: stbi_load_from_file already defined in nanovg.lib(nanovg.c.obj)
16:03:10:503	2>soil2.lib(SOIL2.c.obj) : error LNK2005: stbi_load_gif_from_memory already defined in nanovg.lib(nanovg.c.obj)
16:03:10:503	2>soil2.lib(SOIL2.c.obj) : error LNK2005: stbi_load_16_from_memory already defined in nanovg.lib(nanovg.c.obj)
16:03:10:503	2>soil2.lib(SOIL2.c.obj) : error LNK2005: stbi_load_16_from_callbacks already defined in nanovg.lib(nanovg.c.obj)
16:03:10:568	2>soil2.lib(SOIL2.c.obj) : error LNK2005: stbi_load_16 already defined in nanovg.lib(nanovg.c.obj)
16:03:10:568	2>soil2.lib(SOIL2.c.obj) : error LNK2005: stbi_load_from_file_16 already defined in nanovg.lib(nanovg.c.obj)
```

**Comment by SpartanJ** [comment]
Comment the `#define STB_IMAGE_IMPLEMENTATION` on [nanosvg](https://github.com/memononen/nanovg/blob/master/src/nanovg.c#L29C1-L29C33) or [SOIL2](https://github.com/SpartanJ/SOIL2/blob/master/src/SOIL2/SOIL2.c#L112). SOIL2 patches stb_image to enhance its capabilities, I cannot do much about this issue, also it's trivial to disable the compilation on one of the sides.

**Comment by jjYBdx4IL** [comment]
well, both projects could at least customize the used "namespace". Just prepend soil2__ to every stb function.

**Comment by jjYBdx4IL** [comment]
Btw is your updated STB lib backwards compatible? Could I simply back it out of Soil2 and run NanoVG against it?

**Comment by SpartanJ** [comment]
Yes, you should have no problem, it's the same API.

**Comment by jjYBdx4IL** [comment]
thx
